### ISSUE TITLE
Missing word in README.md

### ISSUE THREAD

**Issue by jkleiser** [Interana/eventsim#1]
In the following line
"This is written a novice Scala programmer. An expert could improve the code quality."
the word "by" (or maybe "for") seems to be missing. I guess it should have been
"This is written by a novice Scala programmer. ..."

**Comment by funbobby** [comment]
thanks, I just fixed the typo:
https://github.com/Interana/eventsim/commit/a74420b88c952f5a653aeb98c3b384bef93a46d6
